feat: add bu1 module
GoogleCloudPlatform/terraform-example-foundation-app pull request #9
Opened 2021-04-02 22:15 UTC by rutalreja-deloitte

2021-04-02 23:30 UTC, bharathkkb requested changes
Thanks for the PR @rutalreja-deloitte

2021-04-02 23:30 UTC, bharathkkb commented on 5-infrastructure/business_unit_1/development/development.auto.tfvars
> +gke_mci_cluster_cidr_block = "100.64.70.0/28"
nit: newline

2021-04-02 23:30 UTC, bharathkkb commented on 5-infrastructure/business_unit_1/development/variables.tf
> +  default     = ""
Lets explicitly require these

2021-04-02 23:30 UTC, bharathkkb commented on 5-infrastructure/business_unit_1/development/development.auto.tfvars
> +terraform_service_account  = "terraform-boa-sa@prj-d-shared-base-f12c.iam.gserviceaccount.com"
Lets explicitly set all these as examples following example-foundation conventions so it is clear to the user that this needs to me changed.
https://github.com/terraform-google-modules/terraform-example-foundation/blob/b1704781ba4a004de5ba8917feded5361259ce12/3-networks/common.auto.example.tfvars#L19

2021-04-02 23:30 UTC, bharathkkb commented on 5-infrastructure/modules/base-env/README.md
> +# Base Env Module
This is in the other PR, lets remove this from here and we can rebase when the other PR is merged

2021-04-06 06:36 UTC, rutalreja-deloitte commented
Ready apart from pull from main once base-env merges, then lint will pass

2021-04-06 15:18 UTC, bharathkkb commented
@rutalreja-deloitte other PR is merged

2021-04-06 18:02 UTC, closed without merging